### ISSUE TITLE
OLED Display is gone

### ISSUE THREAD

**Issue by ubx** [pjalocha/esp32-ogn-tracker#2]
Hi

After flashing the newest version to my HELTEC module, the OLED display is black. I uncommented 
`#define WITH_HELTEC`  and `#define WITH_OLED` in hal.h.

Checked out from a5dbd28bb891fc7d1dc3af19caabae36e5c894d3 and the OLED works as expected.

**Comment by pjalocha** [comment]
Hello Andreas, I will check this, must be resolveable.

Pawel.

**Comment by amlecka** [comment]
Hi, I had the same problem, after editing config.h it works all perfectly!
Adam

**Comment by ubx** [comment]
Hi Pawel
Adam is right, after editing config.h it works now es expected!
Andreas
