### ISSUE TITLE
TBEAM

### ISSUE THREAD

**Issue by lupus78** [pjalocha/esp32-ogn-tracker#8]
Has anyone been able to complie and use this on a TBEAM board, specifically this:
https://www.aliexpress.com/item/33043804231.html?spm=a2g0s.9042311.0.0.7b1c4c4dfuXKS0

I changes the config.h, it complies and flashed but never connects to the GPS.

**Comment by pjalocha** [comment]
Yes, it is a new T-Beam with AXP192 chip which controls charging and power.
It is under control, the code should appear here soon.

**Comment by lupus78** [comment]
This works pretty well. I close this issue... if I can :)
